title: Caitlin Gilbert # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  PhD in Neuroscience with expertise in data science, epigenomics, linguistics, science writing and communication. For my academic work, I developed skillsets in data mining, statistical modeling, machine learning, and visualization. I have additional data science expertise from work with political nonprofits, election data projects, and mis/disinformation research across social media.
  <br><br>
  New York, NY 
  <br><br>
  <a href="https://www.linkedin.com/in/caitlin-gilbert/">LinkedIn</a> | <a href="https://www.github.com/caitlingilbert/">Github</a>
  
theme: jekyll-theme-minimal
google_analytics: 171530521

