title: Caitlin Gilbert # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Reporter @ The Washington Post. For my neuroscience PhD work on songbird brains, I developed skillsets in data mining, statistical modeling, machine learning, and visualization. 
  <br><br>
  Expertise: the brain / linguistics / elections / disinformation / genomics
  <br><br>
  <a href="https://www.washingtonpost.com/people/caitlin-gilbert/">Washington Post author page</a> | <a href="https://www.ft.com/caitlin-gilbert/">Financial Times author page</a> | <a href="https://www.linkedin.com/in/caitlin-gilbert/">LinkedIn</a> | <a href="https://www.github.com/caitlingilbert/">Github</a>
  
theme: jekyll-theme-minimal
google_analytics: 171530521

