title: Caitlin Gilbert # your name (or website title) here
logo: "/images/CODCHw0A_400x400.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD Candidate in Neuroscience with expertise in neurobiology, data science, science writing and communication. My thesis aims to understand the genetic underpinnings of speech/language acquisition. For this work, I have developed skillsets in data mining, statistical modeling, machine learning, and visualization.
  <br><br>
  New York, NY 
  <br><br>
  <a href="https://www.linkedin.com/in/caitlin-gilbert/">LinkedIn</a> | <a href="https://www.github.com/caitlingilbert/">Github</a>
  
theme: jekyll-theme-minimal
google_analytics: 171530521

